### PR TITLE
Optional ability to use custom route

### PR DESCRIPTION
**Pull request by drionix**
Using custom routes gives the ability to customize the controller provided

### CODE REVIEW

**Comment by mabasic** [comment]
What is the benefit of this?

Could you write a line or two for me to understand the use case.

**Comment by drionix** [comment]
Use everything this package provide, but with additional logic for controller.
Etc: adding custom logic for comment approval, or maybe ajax-paginating comment, or whatever logic. Just name it.

**Comment by mabasic** [comment]
Ok, I do not like the implementation, but I understand what you need. Give me some time to implement this

**Comment by mabasic** [comment]
Fixed in  62c357f

**Pull request closed without merging**
