### PR TITLE
Make auth guards configurable through package configurations

### PR DESCRIPTION
**Pull request by eworwa**
Hi @mabasic , again thanks for this awesome package.

While working for supporting multiple authenticable models I faced and issue for making other models available for the routes defined in this package.

When we were talking about this feature (PR [#49](https://github.com/laravelista/comments/pull/49)) I mentioned that I was using a custom middleware for making the new authenticable model available for the comments routes. However (I'm still finding my way around Laravel), I was confused by the time with the whole concept of middlewares/guards (tbh, I'm still a little confused). Anyway, what I meant by the time is that I was using a custom **guard**. So, in my config/auth.php file I have the following:

```
'guards' => [
        'web' => [
            'driver' => 'session',
            'provider' => 'users',
        ],
        'chat' => [
            'driver' => 'session',
            'provider' => 'participants',
        ],

        'api' => [
            'driver' => 'token',
            'provider' => 'users',
        ],
    ],

'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],

        'participants' => [
            'driver' => 'eloquent',
            'model' => App\Models\Participant::class,
        ],
    ],
```

Now, this PR exposes a new configuration, `comments.aut_guard`, and is implemented in the in the constructor for CommentControler.php. This update is fairly simple and I don't think it'll break any functionality, however, I'm not sure this is the best way to implement this or even if it's the Laravel way to do it so any advice on this would be greatly appreciated.

Happy to discuss this issue further, let me know if you need any other info from me.

Thanks,

Enrique

### CODE REVIEW

**Comment by mabasic** [comment]
If I understand you correctly, you are using custom middleware for auth or middleware other than `web` for the controller?

Since using custom auth and custom web middleware is very custom :) I think that this should not be a part of this package now.

You can extend the controller for comments in your application and use the [config](https://github.com/laravelista/comments/blob/master/config/comments.php#L28) to point to your custom CommentController where you can define controller middleware however you want.

```
namespace App\Http\Controllers;

use  Laravelista\Comments\CommentController;

class CustomCommentController extends CommentController
{
    /**
     * Override constructor with your code.
     */
    public function __construct()
    {
        $this->middleware('web'); // attach your middleware

        if (config('comments.guest_commenting') == true) {
            $this->middleware('auth')->except('store'); // attach your middleware 
        } else {
            $this->middleware('auth');// attach your middleware 
        }
    }
```

Let me know what you think of this.

**Comment by eworwa** [comment]
Hi @mabasic ,

I think you're right, my particular use case is not even about a custom middleware but about a custom provider for the auth middleware, which it is a very particular requirement.

Even more, in the latest version of this package (3.0.0 as per this comment date), it is possible to achieve what I need in the way you stated in previous comment so feel free to close this PR.

Thanks for all the work on this package,

Enrique

**Comment by eworwa** [comment]
Hi @mabasic ,

I think you're right, my particular use case is not even about a custom middleware but about a custom provider for the auth middleware, which it is a very particular requirement.

Even more, in the latest version of this package (3.0.0 as per this comment date), it is possible to achieve what I need in the way you stated in previous comment so I'm gonna close this PR.

Thanks for all the work on this package,

Enrique

**Comment by mabasic** [comment]
Great that this can be solved now.

No no, thank you for contributing.

**Pull request closed without merging**
