### PR TITLE
Ability to see deleted comments

### PR DESCRIPTION
**Pull request by S-DICKSON**
Added this functionality. 	

``
@comments(['model' => $model, 'withTrashed' => true])
``

image

Not sure if you want this or not so happy to close PR if not required.

I've not tested this yet with models that don't have soft deletes so there is still work required in this PR.

### CODE REVIEW

**Comment by mabasic** [comment]
What is the use case for showing deleted comments?

**Comment by S-DICKSON** [comment]
> What is the use case for showing deleted comments?

A social media moderator for a group page could look at a post that has comments and check nothing has been posted that is inappropriate even if it's been deleted.

**Comment by mabasic** [comment]
I will accept this PR once completed. Let me know when it is ready. Thank you for your contribution.

**Comment by Shubhamlmp** [comment]
@mabasic  Info from https://repo.packagist.org: #StandWithUkraine
Using version ^4.5 for laravelista/comments
./composer.json has been updated
Running composer update laravelista/comments
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravelista/comments ^4.5 -> satisfiable by laravelista/comments[4.5.0].
    - laravelista/comments 4.5.0 requires illuminate/database ^8.0 -> found illuminate/database[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require laravelista/comments:*" to figure out if any version is installable, or "composer require laravelista/comments:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by S-DICKSON** [comment]
I'm sorry, I don't have the time to work on it. If people require it in the future, I'll happy to develop it :)

**Pull request closed without merging**
