### PR TITLE
Add basic spam protection

### PR DESCRIPTION
**Pull request by rocramer**
Basic spam protection integrated with the help of [Laravel Honeypot](https://github.com/spatie/laravel-honeypot):

> When adding a form to a public site, there's a risk that spam bots will try to submit it with fake values. Luckily, the majority of these bots are pretty dumb. You can thwart most of them by adding an invisible field to your form that should never contain a value when submitted. Such a field is called a honeypot. These spam bots will just fill all fields, including the honeypot.

The advantage of this package is, that the user do not have to fill out anything and the website owner has no problems with data privacy laws (especially in the EU) because no third party is involved. I think the package is a good starting point for securing forms.

I just secured the `create` route because this is the only route used by guests.

### CODE REVIEW

**Comment by mabasic** [comment]
Hi again,

I like this. 

Can you move the middleware to the controller constructor instead? Or if you don't have time I can move it...

**Comment by mabasic** [comment]
Nice, but now it is active for all routes :) It just needs to be enabled for the `store` method.

Let me make the changes. This middleware needs to be attached only if the guest commenting is enabled and the user is not logged in.

**Comment by rocramer** [comment]
Okay, I thought you wanna check all routes because you talked about the constructor. :-) Change it like it suits you in the end. But the current solution is working as well because there is no disadvantage to spam check logged in user as well.

If user of the package are changing the policy and  e.x allowing guests to reply on comments, the route is spam protected as well in the current implementation. So in the end it might make sense to protect them in advance.

**Comment by mabasic** [comment]
I've made some changes so that it the spam middleware is only activated on the store method if guest commenting is enabled.

Thank your for this PR :heart:

**Pull request merged**
