### PR TITLE
Comment model class stored as a package setting.

### PR DESCRIPTION
**Pull request by eworwa**
Hi,

First of all thanks for building this package, its been quiet useful and saved me a lot of development time.

While using this package a requirement arise: to attach multimedia files to comments, been the relationship 1:*.

Now, when trying to implement this requirement I had the following issues:

- I couldn't just extend the base Comment model shipped with the package because I would also need to extend the controller, approach that I think wouldn't be scalable.

- When trying to use events to hook into the CRUD process, I realized that even extending the Comment model and implementing the relationship to Media, I wouldn't be able to use this new relationship in events since the passed down model is the base model shipped with the package, and for updating this I also would need to extend the controller.

So I wrote a little update for this module to make it easier to extend the base Comment model while keeping all the package functionalities. The approach I followed is:

- Created a configuration for storing the class of the Comment model (default to the one shipped with this package).

- In the package service provider, create a route model binding using the new created configuration.

- Updated to store method in the CommentController to implement the new config for the Comment model.

This way, someone that wants to extend the base Comment model just needs to create a new CustomComment model (or whatever they want to call it) extending the Comment model shipped with the package and update the configuration storing what model the package should use. The controller will still use the right Model (cause the route model binding), and particularly the store method in the controller now implements the model class stored in the config file.

I hope all this is clear, my experience with Laravel is rather limited, but I think this changes won't affect previous implementations and is working very well to me.

Happy to discuss this or any other approach you consider might be best.

Thanks,

Enrique

### CODE REVIEW

**Comment by mabasic** [comment]
Hi Enrique,

I'm glad that you like this package and that you find it helpful.

Your PR is great and I think that the functionality for what you are using it is interesting. 
I will need to add docs to this PR before merging, but thank you.

I have a question for you regarding multimedia files (attachments, files etc...) in comments what you mentioned. Are you willing to extend this package to support attachments. I'm not sure if I want them to be here by default, but maybe an extra package which adds supports for attachments or optional... Does this make sense to you and are you interesting in doing this with me?

**Comment by eworwa** [comment]
Hi @mabasic ,

I'm of the preference of having a package handling one and just one feature, and then implement any other package to extend its functionality.

For example, for this particular project I'm working on, I already have in place all the logic around Media handling, so this update (PR) made it way easier to implement this functionality by just including a trait in the extended Comment model and hooking into the dispatched events.

Even more, I found a couple of media handling packages for Laravel (haven't try it yet) that are very easy to integrate with your package (after this update merge into master) in the same way stated above:

- [https://github.com/plank/laravel-mediable](https://github.com/plank/laravel-mediable)

- [https://github.com/spatie/laravel-medialibrary](https://github.com/spatie/laravel-medialibrary)

The same way we could extend your package to support voting for example (as I read in one of the issues), so I'd advice against implementing media handling directly into this package.

Let me know your impressions about this, 

Enrique

**Comment by mabasic** [comment]
Yes, I agree. There is no need for this since there are a lot of packages like you linked above that can be easily implemented with this package.

**Comment by eworwa** [comment]
Hi @mabasic , I pushed some updates to this PR:

- Updated some missing relationships to use the new configuration.

- Renamed the configuration key name.

**Pull request merged**
